package(default_visibility = ["//visibility:public"])

cc_library(
    name = "user",
    hdrs = ["user.hh"],
    deps = [
        "//cs/net/json:object",
        "//cs/net/json:parsers",
        "//cs/net/json:serialize",
        "//cs/result",
    ],
)
