package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ensure",
    srcs = ["ensure.cc"],
    hdrs = ["ensure.hh"],
)

cc_library(
    name = "error",
    srcs = ["error.cc"],
    hdrs = ["error.hh"],
)
