package(default_visibility = ["//visibility:public"])

cc_library(
    name = "matrix4x4",
    srcs = ["matrix4x4.cc"],
    hdrs = ["matrix4x4.hh"],
    deps = [
        "//cs/numbers:in_range",
        "//cs/sanity:ensure",
        "//cs/string:format",
    ],
)
