#ifndef CS_APP_SCENE1_HH
#define CS_APP_SCENE1_HH

#define APP_FRAME_RATE_FPS 24
#define APP_ANIMATION_DURATION_SEC 5
#define APP_NUM_FRAMES \
  (APP_FRAME_RATE_FPS * APP_ANIMATION_DURATION_SEC)
#define APP_ANIMATION_NUM_FRAMES \
  (APP_FRAME_RATE_FPS * APP_ANIMATION_DURATION_SEC)
#define APP_SCREEN_WIDTH 256
#define APP_SCREEN_HEIGHT 256

#endif  // CS_APP_SCENE1_HH