package(default_visibility = ["//visibility:public"])

cc_library(
    name = "constants",
    hdrs = ["constants.h"],
)

cc_library(
    name = "polar2cart",
    srcs = ["polar2cart.cc"],
    hdrs = ["polar2cart.hh"],
    deps = ["//cs/geo:point3"],
)
