on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: make setup

      - name: Build
        run: make build

      - name: Test
        run: make test
